/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

/**
 *
 * @author wintwinthtae
 */
import Connections.ConnectionToDB;
import Forms.Login;
import Student.AddStudents;
import Admin.AddCandidatesPanel;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public AdminPanel() {
        initComponents();
        conn = ConnectionToDB.ConnectToDB();
	         this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);

	       //  displayBarChart();
    }

    public void close(){
	        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
	        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
	    }

    public void displayBarChart(){
		    try{
		            String sql = "SELECT firstname , vote_count FROM candidates_info";
		            JDBCCategoryDataset dataset = new JDBCCategoryDataset(ConnectionToDB.ConnectToDB(),sql);
		            JFreeChart chart = ChartFactory.createLineChart("Pie Chart Title","First Name","Vote Count", dataset,PlotOrientation.VERTICAL ,false,true,true);
		            BarRenderer render = null;
		            CategoryPlot plot = null;
		            render = new BarRenderer();
		            
		      
		            ChartFrame frame = new ChartFrame("Query Chart",chart);
		            frame.setExtendedState(frame.getExtendedState() | JFrame.MAXIMIZED_BOTH);
		            frame.setSize(1353, 697);
		            frame.setResizable(false);
		            frame.setVisible(true); 
		           
		        }catch(Exception e){
		            JOptionPane.showMessageDialog(null, e);
		        }
		    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addCandidatesItem = new javax.swing.JButton();
        addUserItem = new javax.swing.JButton();
        addStudentItem = new javax.swing.JButton();
        viewVotesItem = new javax.swing.JButton();
        exitItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        addCandidatesItem.setBackground(new java.awt.Color(218, 190, 255));
        addCandidatesItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addCandidatesItem.setText("Add Candidate");
        addCandidatesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidatesItemActionPerformed(evt);
            }
        });

        addUserItem.setBackground(new java.awt.Color(218, 190, 255));
        addUserItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addUserItem.setText("Add User");
        addUserItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserItemActionPerformed(evt);
            }
        });

        addStudentItem.setBackground(new java.awt.Color(218, 190, 255));
        addStudentItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addStudentItem.setText("Add Student");
        addStudentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentItemActionPerformed(evt);
            }
        });

        viewVotesItem.setBackground(new java.awt.Color(218, 190, 255));
        viewVotesItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewVotesItem.setText("View Votes");
        viewVotesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVotesItemActionPerformed(evt);
            }
        });

        exitItem.setBackground(new java.awt.Color(218, 190, 255));
        exitItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/png1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addStudentItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addCandidatesItem, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(addUserItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewVotesItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addUserItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(addCandidatesItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(addStudentItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(viewVotesItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addComponent(exitItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentItemActionPerformed
        // TODO add your handling code here:
        AddStudents ad = new AddStudents();
        ad.setVisible(true);
    }//GEN-LAST:event_addStudentItemActionPerformed

    private void addUserItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserItemActionPerformed
        // TODO add your handling code here:
        AddUser au = new AddUser();
        au.setVisible(true);
    }//GEN-LAST:event_addUserItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        //close();
        l.setVisible(true);
    }//GEN-LAST:event_exitItemActionPerformed

    private void addCandidatesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidatesItemActionPerformed
        // TODO add your handling code here:
         AddCandidatesPanel acp = new AddCandidatesPanel();
         acp.setVisible(true);
    }//GEN-LAST:event_addCandidatesItemActionPerformed

    private void viewVotesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVotesItemActionPerformed
        // TODO add your handling code here:
        ViewVotesPanel vvp = new ViewVotesPanel();
        //close();
        //
        vvp.setVisible(true);

    }//GEN-LAST:event_viewVotesItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCandidatesItem;
    private javax.swing.JButton addStudentItem;
    private javax.swing.JButton addUserItem;
    private javax.swing.JButton exitItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewVotesItem;
    // End of variables declaration//GEN-END:variables
}
